// ERR

func test() {
    return;
}

func main() {
    print(test())
}