// ERR

fun test() {
    print("oh no");
}

func main() {
    test(42)
}