// ERR

fun test(String a) {
    print(a);
}

func main() {
    test(42)
}