// ERR

fun test(a: String) {
    print(a);
}

func main() {
    test(42)
}